#和02组成高可用的eureka集群
spring:
  application:
    name: eureka-server-hight
server:
  port: 8761 #默认的端口
eureka:
  instance:
    hostname: eureka01 #主机名字 不配置的时候根据操作系统的主机名来获取
    prefer-ip-address: true #页面显示的是ip+端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:    #注册中心对外暴露的注册地址
      defaultZone: http://localhost:8762/eureka/